---
kind: pipeline
type: docker
name: default

trigger:
  ref:
    - refs/heads/main
    - "refs/tags/**"
    - "refs/pull/**"

steps:
  - name: install dependencies
    image: node:16-alpine
    commands:
      - npm install

  - name: lint
    image: node:16-alpine
    commands:
      - npm run lint

  - name: build
    image: node:16-alpine
    commands:
      - npm run build

  - name: publish
    image: plugins/npm
    settings:
      token:
        from_secret: npm_token
    when:
      event:
        - tag
